### PR TITLE
Update container interface

### PR DESCRIPTION
**Pull request by rtholmes**
See #117 for a complete list of tasks.

### CODE REVIEW

**Comment by nickbradley** [comment]
I'm sure those will break the tests. If you are okay with the changes, I'll fix up the tests and make the changes to the container.

**Comment by rtholmes** [comment]
Looks good to me, go for it!

**Comment by nickbradley** [comment]
This should be it for my changes. Let me know before you merge so we can coordinate the container updates.

**Comment by rtholmes** [comment]
Great @nickbradley; let's aim for Tuesday am?

**Comment by rtholmes** [comment]
Pulled in master and resolved conflicts so final deploy should be smooth sailing.

**Pull request merged**
