### PR TITLE
Add the ability to selectively choose files to provision/clone

### PR DESCRIPTION
**Pull request by jopika**
Adding this feature will extend the current behavior in a non-intrusive way, allowing the ability to choose a subdirectory to seed repositories.

### CODE REVIEW

**Comment by jopika** [comment]
Aside: I'm not sure how I would simplify/remove redundant code here:
https://github.com/ubccpsc/classy/compare/feature/dynamicRepoProvisionPath?expand=1#diff-0f99b066bc50c3e08f613a9e5593262fR593

I don't really understand how to chain the promises in a way that would allow that.

**Comment by rtholmes** [comment]
I think what we actually want to do here is separate creating repositories
from provisioning them. So rather than specializing this one huge
provisioning step, we should pull out the creation code and then make it so
you can perform whatever provisioning steps you want.

**Comment by rtholmes** [comment]
No, what I mean is we can have two high-level methods: one provisions repos and teams, the other populates the repo (e.g., takes a `Repository` object and some kind of source (be that another repo, or a repo and a dir) and does the copying). I'll look at the API and we can see what we can come up with.

**Comment by jopika** [comment]
Features have been moved to `master` branch, as of 7293337f0c4ebb7fb3386d6589bd460dd2eca7f8.

**Pull request closed without merging**
