### PR TITLE
Add the ability to specify Custom team names

### PR DESCRIPTION
**Pull request by jopika**
## Team names can now be specified for the Staff and Admin lists
This allows for instructors to use a custom team name so they can be more specific about which Github team to check for Admins and Staff when deploying.

### CODE REVIEW

**Comment by andrewstec** [comment]
@jopika 

I am not too sure if we need this change to the code at the moment. These are some of the few constant fields that exist in the integration logic between Classy and Github. 

From an operations perspective, it is nice to have these constants. It potentially allows for more setup automation. 

Was there a key issue that you wanted to solve by parameterizing these fields? I am just curious if that business logic will apply to other courses.

**Comment by winstan** [comment]
I think this is related to the idea of using the same Classy instance split among sections (MDS wanting to use some number of courses on one instance.).

**Comment by andrewstec** [comment]
> I think this is related to the idea of using the same Classy instance split among sections (MDS wanting to use some number of courses on one instance.).

In that case, this would be a pretty specific MDS use-case. It may sound tempting to add this capability in, as more customization exists, but it creates another inconsistency between courses, which I do not think is desirable at this point.

**Comment by andrewstec** [comment]
@jopika Anthony recalls us agreeing to this change at an earlier time to help accommodate your customization, so we can accept this pull-request.

We cannot accept this pull-request just yet, as we have some failing CI tests due to a feature change that we need to implement and this PR requires that we update the CircleCI testing configuration files so they have these additional parameters. 

Are you ready to open this PR to review or is there anything else that you would like to discuss?

**Comment by andrewstec** [comment]
Blocked by: https://github.com/ubccpsc/classy/issues/319

**Comment by andrewstec** [comment]
> Blocked by: #319

No longer blocked. 

Ready to merge once @jopika approves.

**Pull request merged**
